apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
    - name: app.rules
      rules:
        - alert: AppReplicaCountLow
          expr: |
            kube_deployment_status_replicas_available{namespace="default", deployment="project2"} < 3
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "Low number of running replicas"
            description: "Deployment project2 has fewer than 3 available replicas for more than 2 minutes."
